djangoapp/accounts/urls.py
from django.urls import path, re_path
from . import views

app_name = 'accounts'

urlpatterns = [
 path('signup/', views.signup_view, name="signup"),
 path('login/', views.login_view, name='login'),
 path('logout/', views.logout_view, name='logout')
]

djangoapp/articles/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = 'articles' #namespacing our url #remember that to access variables you need to wrtie 'articles:smt'

#url patterns for our articles module app section or whatever it's called

urlpatterns = [
    path(r'', views.article_list , name='list'), #homepage that's only .com\ list url we want to go
    path('create/', views.article_create, name = 'create'),
    path("<slug:slug>/", views.article_detail, name='detail')
    #re_path(r'^(?P<slug>[\w-]+)/$', views.article_detail)
    #we need catch group that we give name slug
    # with regex which going to second argument in article_detail  [\w-]+/ any letter with - sign with /at the end
]

djangoapp/djangoapp/urls.py
from django.contrib import admin
from django.urls import path , include # function which will include urls from other apps
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views  as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path(r'articles/', include('articles.urls')), #now django knows about our articles urls app and includes them
    path(r'about', views.about ),  #this is for our about page url pattern (that is only about/)
    path(r'', article_views.article_list, name='home' ) #homepage that's only .com\

]

urlpatterns += staticfiles_urlpatterns() # if we are in debug mode it will append our static files
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) #setting up phase for uploading files
#specyfing to which url we are uploading and to which dir should the uploaded files go 

djangoapp/accounts/models.py
from django.db import models

# Create your models here.

djangoapp/articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
 #specyfiing the tpye of our fields
class Article(models.Model): 
    title=  models.CharField(max_length = 100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    thumb = models.ImageField(default="default.png", blank=True) #it can be  blank filed
    author =models.ForeignKey(User, on_delete = models.PROTECT, default = None)


    #defing how ist gonna look
    #
    def __str__(self):
        return self.title
    def snippet(self):
        return self.body[:50] + '...'
        
#if the field is created it will automatically initialize the value
#add in thumbnail later and also add author later
#todo make migration so that this model is mapped to  database table
#now making migration file which tracks any changes made to a model

#everytiem we make changes to our models we need to run
#python manage.py makemigrations
#python manage.py migrate

djangoapp/articles/forms.py
from django import forms
from .import models
#model forms 
# something like usercreation form 
class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title','body','slug','thumb']
        #we created our model form which will take 4 fields

djangoapp/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST) #giving the post data
        if form.is_valid():
            user =  form.save() #it returns the ruser
            login(request,user) 
            #to do log user in 
            #sending the user if he logged
            return redirect("articles:list")
    else:        
        form = UserCreationForm()
    return render(request,'accounts/signup.html', { 'form':form })
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log the user in 
            user = form.get_user() #accesingthe user djangfo mmethod 
            login(request,user) #logginh the user by django login funciotn 
            if 'next' in request.POST: 
                return  redirect(request.POST.get('next'))
            else:
                return redirect("articles:list")
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request) #django knows which user is curenntly logged
        return redirect('articles:list')
    else:
        logout(request)
        return redirect('articles:list')

djangoapp/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date') #ordering retrived our files by date
    return render(request, "articles/article_list.html",{ 'articles' : articles})
    #specyfing so that django will know which to render 
    #its called namespaceing i think 
    #now we have to register this app
def article_detail(request,slug):
     #return HttpResponse(slug)
     article = Article.objects.get(slug = slug) #quering our database to find the article with given slug
     return render(request,'articles/article_detail.html', { 'article': article})

@login_required(login_url='accounts:login')     #that way if somebody wants to access this page user must be logged in 
def article_create(request):
    if request.method == 'POST':
        #retriving the data
        form = forms.CreateArticle(request.POST,request.FILES)
        print(form.is_valid())
        if form.is_valid() == True:
            #todo saving the article to the db
            instance =form.save(commit=False) #do not commit just yet that why commit is set to false
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request,'articles/article_create.html', {'form': form})

djangoapp/djangoapp/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    #return HttpResponse("homepage")
    return render(request, 'homepage.html')


def about(request):
    return render(request, 'about.html')


djangoapp/accounts/templates/accounts/login.html

{% extends 'base_layout.html' %}

{% block content %}
<h1>Login </h1>
    <form class='site-form' action="{% url 'accounts:login' %}" method="post"> <!--- TODO post request  -->
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
        <input type="hidden" name="next" value= "{{ request.GET.next }}" >
        <!-- that we way we are sending via the post request the 'next' value
             if user is supposed to be redirected alse where-->
        {% endif %}

        <input type="submit" value="login">
    </form>

{% endblock %}

djangoapp/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Sign up</h1>
    <form class='site-form' action="" method="post"> <!--- TODO post request  -->
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="signup">
    </form>

{% endblock %}

djangoapp/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="create-article">
    <h2>Awesome new article</h2>
    <form action="{% url 'articles:create' %}" class="site-form" method="POST" enctype="multipart/form-data">
        {% csrf_token%}
        {{ form }} <!-- this will handle our input field for us by django model forms-->
        <input type="submit" value="Create">
    </form>
</div>
<script type="text/javascript" src="/static/slugify.js"> </script>
{% endblock%}

djangoapp/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}
{% block content %}
    <!--arctuall contnet-->
    <div class="article-detail">
        <div class="article">
            <img src="{{article.thumb.url}}" height='500' width='1000' alt="">
            <h2 class="title">{{ article.title }}</h2>
            <p class="body"> {{article.body}} </p>
            <p class="date">{{article.date}}</p>
        </div>
    </div>

{% endblock %}

djangoapp/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}
{% block content %} <!-- this extending the template in django -->
    <h1>Articles </h1>
    <div class="articles"> <!--  -->  <!-- for outputting data-->
        {% for article in articles %}
         <div class="article"> 
             <h2><a href="{% url 'articles:detail' slug=article.slug %}"> {{article.title}}  </a></h2>
             <p>   {{article.snippet}} </p>
             <p> {{article.date }} </p>
             <p class="author" >added by {{article.author.username}}</p> <!--author is foreign key which has access to the username-->
        {% endfor %}
    </div>
{% endblock %}

djangoapp/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About us</title>
</head>
<body>
    <h1> We like django</h1>
</body>
</html>

djangoapp/templates/base_layout.html
{% load static %} <!-- our common used template which is supposed to be extend by varius blocks-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <!--  <title>Article </title>  -->
</head>
<body>
    {% url 'articles:list' as the_url  %}
    {% if the_url %}
        <header>
            <h1> <a href="{% url 'home' %}"> <img src="{% static 'logo.png' %}" alt="img"> </a> </h1> 
            <nav>
                <ul>
                    {% if user.is_authenticated %} <!--dynamics checking -->
                    <li>
                        <form class='logout-link' action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li>
                        <a class="highlight" href="{% url 'articles:create' %}">Create new article</a class="highlight">
                    </li>
                    {% else %}
                        <li>
                            <a href="{% url 'accounts:login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:signup' %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
    {% endif %}
    <!-- specyfing that we want logo.png for our static files like wise specyfing our url from the name list-->
   <div class="wrapper">
    {% block content %}
    {% endblock %}
   </div>
</body>
</html>

djangoapp/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
</head>
<body>
    <h1> Welcome to homepage</h1>
    <p> Our django app </p>
</body>
</html>